name: Auto Merge

# Automatically merge approved pull requests when all checks pass
# This helps maintain velocity while ensuring quality

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto Merge Approved PRs
    runs-on: ubuntu-latest
    
    # Only run for approved reviews
    if: (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') || github.event_name == 'check_suite'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "automerge,!work-in-progress,!do-not-merge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"

      - name: Comment on merged PR
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              github.rest.issues.createComment({
                issue_number: pr.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '🎉 **Auto-merged!**\n\nThis PR was automatically merged because:\n- ✅ All checks passed\n- ✅ PR was approved by a maintainer\n- ✅ Contains the `automerge` label\n\nThank you for your contribution! 💙'
              })
            }
