name: Format Check

# Run on pull requests to ensure consistent code formatting
on:
  pull_request:
    branches: [main]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
      - '**.mjs'
      - '**.css'

jobs:
  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint check
        run: npm run lint
        continue-on-error: false

      - name: Check for formatting issues
        run: |
          echo "✅ Code formatting is consistent!"
          echo "All ESLint rules are satisfied."

      - name: Comment on PR (if formatting issues found)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Formatting Issues Detected**\n\nPlease run `npm run lint` locally and fix any linting errors before merging.\n\nYou can also check the workflow logs for more details.'
            })
